### ISSUE TITLE
GET url 404 (Not Found) error on user query search

### ISSUE THREAD

**Issue by emanuelefavero** [bradtraversy/github-finder-app#13]
after cloning the repo and npm install I get this error when trying to search a user:

GET http://localhost:3000/search/users?q=brad 404 (Not Found)

Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:66:1)

**Comment by emanuelefavero** [comment]
I think I forgot to edit the .env.example file.

now i got another error:

Failed to load resource: the server responded with a status of 401 ()
Uncaught (in promise) Error: Request failed with status code 401
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:66:1)

**Comment by emanuelefavero** [comment]
I generated a new token and now the app is working again.

For whatever reason my old token stopped working after deploying the app with vercel.
